### PR TITLE
Changed tabs color

### PR DESCRIPTION
**Pull request by spark-lex**
I made a pool in discord server (https://discord.com/channels/911440744621961277/1008828541850374204/1008962781636214804)

And people more liked this fork so I decided to change it.

### CODE REVIEW

**Comment by spark-lex** [comment]
tl;dr made some themes look better and fixed mist theme editor

**Comment by Tamim468** [comment]
you didnt even fix mist theme logo color (it was supposed to be black, it changed to white in the current build unlike previous build and i dont know if it was on purpose.)

**Comment by spark-lex** [comment]
> you didnt even fix mist theme logo color (it was supposed to be black, it changed to white in the current build unlike previous build and i dont know if it was on purpose.)

it was black for me when i was making changes
if you need, you can make ur own pr and fix it

**Comment by Tamim468** [comment]
> > you didnt even fix mist theme logo color (it was supposed to be black, it changed to white in the current build unlike previous build and i dont know if it was on purpose.)
> 
> it was black for me when i was making changes if you need, you can make ur own pr and fix it

after i reinstalled v3, it still occured for me. thank you for your understanding though as i made a pull request for it.

**Comment by ccreaper** [comment]
Approved.

**Pull request merged**
